version: '3'

services:
  mybroker:
    image: 'rabbitmq:3-alpine'

  myredis:
    image: 'redis:alpine'

  mypg:
    image: 'postgres:alpine'
    environment:
      - POSTGRES_PASSWORD=mysecretpass
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
    volumes: 
      - ./pgdata:/var/lib/postgresql/data

  myapi:
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./mybackend
    command:
      sh -c "node index.js"
    volumes:
      - /opt/app/node_modules
      - ./mybackend:/opt/app
    environment:
      - POSTGRES_PASSWORD=mysecretpass
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_HOST=mypg
      - POSTGRES_PORT=5432
      - REDIS_HOST=myredis
      - REDIS_PORT=6379
    ports:
      - "5000:5000"

  myimageuploader:
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./myimageuploader
    command:
      sh -c "node index.js"
    volumes:
      - /opt/app/node_modules
      - ./myimageuploader:/opt/app  
      - web_data:/opt/app/shared
    ports:
      - "5050:5050"      

  myweb:
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./myfrontend
    environment: 
      CHOKIDAR_USEPOLLING: "true"
    command:
      sh -c "npm start"
    volumes:
      - /opt/app/node_modules
      - ./myfrontend:/opt/app

  mynginx:
    restart: always
    build: 
      dockerfile: Dockerfile
      context: ./mynginx
    ports: 
      - "9090:80"

  myworker:
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./BrightnessVerifier
    command:
      scala verifier.jar
    depends_on: 
      - mybroker
    volumes: 
      - web_data:/opt/app/shared

volumes:
  web_data:
    